version: '3'
services:
  api:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app:cached
    command: ['npm', 'run', 'dev']

  db:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
